name: HVolkoff's Arch Repo

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0

      - name: Build packages on Archlinux docker
        run: |
          docker run \
            -w /src \
            -v "$(pwd)":/src \
            -e PUID="$(id -g)" \
            -e PGID="$(id -g)" \
            -e REPO="hvolkoff" \
            -e GIT_AUTHOR_NAME="github-actions[bot]" \
            -e GIT_COMMITTER_NAME="github-actions[bot]" \
            -e EMAIL="github-actions[bot]@users.noreply.github.com" \
            -e GIT_COMMITTER_EMAIL="github-actions[bot]@users.noreply.github.com" \
            -e GIT_COMMITTER_EMAIL="github-actions[bot]@users.noreply.github.com" \
            --rm --init --entrypoint bash \
            archlinux:latest repo.sh
