name: HVolkoff's Arch Repo

on:
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACMAN_ARGS: --needed --noconfirm --noprogressbar
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup build environment
        uses: docker://archlinux:latest
        run: |
          set -xeu
          # makepkg needs a non root user
          useradd builder -m
          echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R builder:builder .
          # Make output repository for pakcages
          mkdir .repo
          # Change some makepkg options
          cp /etc/makepkg.conf ./
          sed -i 's@^#?PKGEXT=.*$@PKGEXT=.pkg.tar.zst@' ./makepkg.conf
          sed -i "s@^#?PKGDEST=.*$@PKGDEST=$(pwd)/.repo@" ./makepkg.conf
          # Add zuepfe-original repo for pacman-hacks
          cat << EOF >> /etc/pacman.conf
          [zuepfe-original]
          SigLevel = Required DatabaseRequired
          Server = http://archlinux.zuepfe.net/$repo/os/$arch
          EOF
          pacman-key --recv-keys FE8CF63AD2306FD41A5500E6DCD45EAF921A7822
          pacman-key --recv-keys BFA8FEC40FE5207557484B35C8E50C5960ED8B9C
          pacman-key --edit-key FE8CF63AD2306FD41A5500E6DCD45EAF921A7822
          pacman-key --edit-key BFA8FEC40FE5207557484B35C8E50C5960ED8B9C

      - name: Install build dependencies
        run: |
          set -xeu
          pacman -Syu ${PACMAN_ARGS} git base-devel pacman-hacks

      - name: Retrieve current packages in repo
        run: |
         set -xeu
         touch packages.txt
         if curl -L#Of \
            "https://$(echo "$GITHUB_REPOSITORY" | awk -F'/' '{ printf "%s.github.io/%s",$1,$2; }' )/hvolkoff.db"
         then
           tar -tvJ ./hvolkoff.db | grep -e "^d" | awk '{print $6}' | tr -d '/' >> packages.txt
         fi

      - name: Update submodules
        run: |
         set -xeu
         git submodule update --init --remote --recursive

      - name: Build pacakges
        run: |
          set -xeu
          for _path in "$(pwd)"/*; do
            [ -d "$_path" ] || continue
            cd "$_path"
            if [ -f ./PKGBUILD ]; then
              _srcinfo="$(makepkg --printsrcinfo | tr -d "[:blank:]")
              _pkgver="$(echo "$_srcinfo" | awk -F'=' '{ if ($1 == "pkgver") print $2 }')"
              _pkgrel="$(echo "$_srcinfo" | awk -F'=' '{ if ($1 == "pkgrel") print $2 }')"
              _status=0
              for _pkgname in $(echo "$_srcinfo" | awk -F'=' '{ if ($1 == "pkgname") print $2 }'); do
                grep "${_pkgname}-${_pkgver}-${_pkgrel}" ../packages.txt; _status=$(( $? + $_status ))
              done
              if [ "$_status" -ne 0 ]; then
                sudo -H -u builder makepkg -Cfs --config ../makepkg.conf ${PACMAN_ARGS}
              fi
            elif [ -f ./REPKGBUILD ]; then
              _files="$( ls -1a | sort )"
              remakepkg -f
              for _pkg in $(comm -13 <( echo "$_files" ) <( ls -1a | sort )); do
                if ! grep "$_pkg" ../packages.txt; then
                  mv "$_pkg" ../.repo
                fi
              done
            fi
          done

      - name: Update repository packages
        uses: peaceiris/actions-gh-pages@v3
        with:
          keep_files: true
          publish_dir: ./.repo
          github_token: ${{ secrets.GITHUB_TOKEN }}
