name: HVolkoff's Arch Repo

on:
  push:
    branches:
      - main
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build packages on Archlinux docker 
        run: |
          docker run \
            -w /src \
            -v "$(pwd)":/src \
            -e GITHUB_REPOSITORY="$GITHUB_REPOSITORY" \
            --rm --entrypoint bash \
            archlinux:latest repo.sh

      - name: Update repository packages
        uses: peaceiris/actions-gh-pages@v3
        with:
          keep_files: true
          publish_dir: ./.repo
          github_token: ${{ secrets.GITHUB_TOKEN }}
