name: HVolkoff's Arch Repo

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build packages on Archlinux docker 
        run: |
          docker run \
            -w /src \
            -v "$(pwd)":/src \
            -e PUID="$(id -g)" \
            -e PGID="$(id -g)" \
            -e GIT_AUTHOR_NAME="Vítor Vasconcellos" \
            -e GIT_COMMITTER_NAME="Vítor Vasconcellos" \
            -e EMAIL="vasconcellos.dev@gmail.com" \
            -e GIT_COMMITTER_EMAIL="vasconcellos.dev@gmail.com" \
            -e GIT_COMMITTER_EMAIL="vasconcellos.dev@gmail.com" \
            -e GITHUB_REPOSITORY="$GITHUB_REPOSITORY" \
            --rm --init --entrypoint bash \
            archlinux:latest repo.sh

