name: HVolkoff's Arch Repo

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build packages on Archlinux docker 
        run: |
          docker run \
            -w /src \
            -v "$(pwd)":/src \
            -e GITHUB_REPOSITORY="$GITHUB_REPOSITORY" \
            --rm --init --entrypoint bash \
            archlinux:latest repo.sh

